# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'WYWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WYWeather
  pod 'Alamofire', '~> 4.7.0'
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'IHProgressHUD'

end
